# -*- coding: utf-8 -*-
"""Prova

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O11tcDv71-VGKUquBdfW6YviXt58Sww_
"""

import sys
try:
  peso = float(input("Digite seu Peso "))
  if peso == 0:
    print("Não divide por 0")
    sys.exit()

  altura = float(input("Digite sua Altura "))
  imc = peso / (altura **2)
  print(f"Seu IMC é: {imc}")
  if imc < 18.5:
    print("Abaixo do peso")
  elif imc <= 24.9:
    print("Peso normal")
  elif imc <= 29.9:
    print("Sobrepeso")
  elif imc <= 34.9:
    print("Obesidade grau 1")
  elif imc <= 39.9:
    print("Obesidade grau 2")
  else:
    print("Obesidade grau 3")
except ValueError:
  print("Seu  Codígo deu erro")
except:
  print("Erro Seu Numero esta errado Burro")
